import React from "react";
import { Truck, ShieldCheck, Globe, Clock, PackageCheck } from "lucide-react";

export default function ShippingPolicyPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
      <div className="text-center">
        <span className="text-xs font-bold uppercase tracking-wider text-[#064B35] bg-[#EAF4D5] px-3.5 py-1 rounded-full">
          Customer Care
        </span>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-[#111111] mt-3 mb-2">
          Shipping &amp; Delivery Policy
        </h1>
        <p className="text-xs sm:text-sm text-gray-600">
          Last updated: January 2025 • Fast, reliable carbon-neutral delivery
        </p>
      </div>

      {/* 3 Speed Highlights */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-[#FFFDF8] rounded-2xl p-5 border border-[#EDE4D5]">
          <Truck className="w-6 h-6 text-[#064B35] mb-2" />
          <h3 className="font-bold text-sm text-gray-900">Free Standard Shipping</h3>
          <p className="text-xs text-gray-500 mt-1">
            Complimentary on all domestic orders over Rs 50. Arrives in 3–5 business days.
          </p>
        </div>
        <div className="bg-[#FFFDF8] rounded-2xl p-5 border border-[#EDE4D5]">
          <Clock className="w-6 h-6 text-[#064B35] mb-2" />
          <h3 className="font-bold text-sm text-gray-900">Express 2-Day Air</h3>
          <p className="text-xs text-gray-500 mt-1">
            Expedited dispatch via air for Rs 14.99 flat. Orders placed before 1 PM EST ship same day.
          </p>
        </div>
        <div className="bg-[#FFFDF8] rounded-2xl p-5 border border-[#EDE4D5]">
          <Globe className="w-6 h-6 text-[#064B35] mb-2" />
          <h3 className="font-bold text-sm text-gray-900">Worldwide Delivery</h3>
          <p className="text-xs text-gray-500 mt-1">
            Shipping to over 45 countries with prepaid import duties and taxes (DDP).
          </p>
        </div>
      </div>

      {/* Comprehensive Body Content */}
      <div className="bg-white rounded-2xl p-6 sm:p-8 border border-gray-200 text-xs sm:text-sm text-gray-700 space-y-6 leading-relaxed">
        <div>
          <h2 className="text-base font-bold text-[#111111] mb-2">
            1. Order Processing Timeframes
          </h2>
          <p>
            All standard orders are verified, packed, and transferred to our carriers within 24 to 48 business hours. Orders placed over weekends or observed national holidays begin processing on the following business day.
          </p>
        </div>

        <div>
          <h2 className="text-base font-bold text-[#111111] mb-2">
            2. Domestic Shipping Rates &amp; Delivery Estimates
          </h2>
          <div className="overflow-x-auto">
            <table className="w-full text-left border border-gray-100 rounded-lg overflow-hidden my-3">
              <thead className="bg-gray-50 text-[11px] font-bold text-gray-700 uppercase">
                <tr>
                  <th className="p-3">Service</th>
                  <th className="p-3">Delivery Time</th>
                  <th className="p-3">Cost</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-100 text-xs">
                <tr>
                  <td className="p-3 font-semibold">Standard Ground (Orders Rs 50+)</td>
                  <td className="p-3 text-gray-600">3–5 Business Days</td>
                  <td className="p-3 font-bold text-[#064B35]">FREE</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold">Standard Ground (Orders &lt; Rs 50)</td>
                  <td className="p-3 text-gray-600">3–5 Business Days</td>
                  <td className="p-3">Rs 4.99</td>
                </tr>
                <tr>
                  <td className="p-3 font-semibold">Priority Express</td>
                  <td className="p-3 text-gray-600">2 Business Days</td>
                  <td className="p-3">Rs 14.99</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <div>
          <h2 className="text-base font-bold text-[#111111] mb-2">
            3. Carbon-Neutral Shipping Guarantee
          </h2>
          <p>
            Through our partnership with certified offset registries, 100% of the carbon footprint generated by our ground and air freight transit is offset through verified reforestation and solar energy initiatives.
          </p>
        </div>
      </div>
    </div>
  );
}
